//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryBasedPasswords.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DictionaryBasedPasswords.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///of
        ///to
        ///and
        ///a
        ///in
        ///is
        ///it
        ///you
        ///that
        ///he
        ///was
        ///for
        ///on
        ///are
        ///with
        ///as
        ///I
        ///his
        ///they
        ///be
        ///at
        ///one
        ///have
        ///this
        ///from
        ///or
        ///had
        ///by
        ///hot
        ///but
        ///some
        ///what
        ///there
        ///we
        ///can
        ///out
        ///other
        ///were
        ///all
        ///your
        ///when
        ///up
        ///use
        ///word
        ///how
        ///said
        ///an
        ///each
        ///she
        ///which
        ///do
        ///their
        ///time
        ///if
        ///will
        ///way
        ///about
        ///many
        ///then
        ///them
        ///would
        ///write
        ///like
        ///so
        ///these
        ///her
        ///long
        ///make
        ///thing
        ///see
        ///him
        ///two
        ///has
        ///look
        ///more
        ///day
        ///could
        ///go
        ///come
        ///did
        ///my
        ///sound
        ///no
        ///most
        ///number
        ///who
        ///over
        ///know
        ///water
        ///than
        ///call
        ///first
        ///people
        ///may
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_words {
            get {
                return ResourceManager.GetString("common_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ability
        ///able
        ///aboard
        ///about
        ///above
        ///accept
        ///accident
        ///according
        ///account
        ///accurate
        ///acres
        ///across
        ///act
        ///action
        ///active
        ///activity
        ///actual
        ///actually
        ///add
        ///addition
        ///additional
        ///adjective
        ///adult
        ///adventure
        ///advice
        ///affect
        ///afraid
        ///after
        ///afternoon
        ///again
        ///against
        ///age
        ///ago
        ///agree
        ///ahead
        ///aid
        ///air
        ///airplane
        ///alike
        ///alive
        ///all
        ///allow
        ///almost
        ///alone
        ///along
        ///aloud
        ///alphabet
        ///already
        ///also
        ///although
        ///am
        ///among
        ///amount
        ///ancient
        ///angle
        ///angry
        ///animal
        ///announced
        ///another
        ///answer
        ///ants
        ///any
        ///anybody
        ///anyone
        ///anything        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_words_alt {
            get {
                return ResourceManager.GetString("common_words_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anal
        ///anus
        ///arse
        ///ass
        ///ballsack
        ///balls
        ///bastard
        ///bitch
        ///biatch
        ///bloody
        ///blowjob
        ///blow job
        ///bollock
        ///bollok
        ///boner
        ///boob
        ///bugger
        ///bum
        ///butt
        ///buttplug
        ///clitoris
        ///cock
        ///coon
        ///crap
        ///cunt
        ///damn
        ///dick
        ///dildo
        ///dyke
        ///fag
        ///feck
        ///fellate
        ///fellatio
        ///felching
        ///fuck
        ///f u c k
        ///fudgepacker
        ///fudge packer
        ///flange
        ///Goddamn
        ///God damn
        ///hell
        ///homo
        ///jerk
        ///jizz
        ///knobend
        ///knob end
        ///labia
        ///lmao
        ///lmfao
        ///muff
        ///nigger
        ///nigga
        ///omg
        ///penis
        ///piss
        ///poop
        ///prick
        ///pube
        ///pussy
        ///queer
        ///scrotum
        ///sex
        ///shit
        ///s hit
        ///sh1t
        ///slut
        ///smegma
        ///spunk
        ///tit
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swear_words {
            get {
                return ResourceManager.GetString("swear_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aam
        ///aani
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aaron
        ///aaronic
        ///aaronical
        ///aaronite
        ///aaronitic
        ///aarrgh
        ///aarrghh
        ///aaru
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///ababdeh
        ///ababua
        ///abac
        ///abaca
        ///abacay
        ///abacas
        ///abacate
        ///abacaxi
        ///abaci
        ///abacinate
        ///abacination
        ///abacisci
        ///abaciscus
        ///abacist
        ///aback
        ///abacli
        ///abacot
        ///abacterial
        ///abactinal
        ///abactinally
        ///abaction
        ///abactor
        ///abaculi
        ///abaculus
        ///abacus
        ///abacuses
        ///abada
        ///abaddon
        ///abadejo
        ///abadengo
        ///abadia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words_alpha {
            get {
                return ResourceManager.GetString("words_alpha", resourceCulture);
            }
        }
    }
}
